### ISSUE TITLE
Suggestion: allow duck-typing for wait.for.event

### ISSUE THREAD

**Issue by airbinder** [ujc/wait-for-stuff#2]
Hi, first of all, thank you for your great work.

I am using wait-for-stuff as a beforeTest and afterTest hook, for starting serves and database connection for testing purpose.

Now, I am using loopback as my framework, the server / app object has .on and .emit function, but it is not exactly a typeof EventEmitter.

So you see, the wait.for.event function does not work for my case.

My suggestion is to change the line wait-for-stuff/index.js:199, from:

```js
    if (!(emitter instanceof EventEmitter)){
        throw new Error('wait.for.event(..) :: invalid <emitter> argument ' + emitter);
    }
```

to

```js
    if (!(emitter.on && emitter.emit)){
        throw new Error('wait.for.event(..) :: invalid <emitter> argument ' + emitter);
    }
```

Thank you.

**Comment by uri-chandler** [comment]
Done!
Thanks for contributing!
